# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: メモ置き場
email: aki@aki017.info
description: >
  Ruby and C# engineer
url: "https://www.aki017.info"

# Social media profiles - feel free to add more here
social:
  - title: twitter
    url: https://twitter.com/aki017
  - title: github
    url: https://github.com/aki017
  - title: facebook
    url: https://www.facebook.com/akiteru.maeda123
  - title: steam
    url: http://steamcommunity.com/id/aki017

# Build settings
markdown: kramdown
